In [1]:
import numpy as np
import cv2
import glob
from pickle import load
from skimage.feature import hog

model = load(open('model_p.pkl', 'rb'))
scaler = load(open('scaler.pkl', 'rb'))


In [2]:
def get_hog_features(img, orient = 9, pix_per_cell = 8, cell_per_block = 2, 
                    feature_vec=True):
    features = hog(img, orientations=orient, 
                   pixels_per_cell=(pix_per_cell, pix_per_cell),
                   cells_per_block=(cell_per_block, cell_per_block), 
                   transform_sqrt=True, 
                   feature_vector=feature_vec)
    return features

def transform(image, size = 128):
    img = cv2.imread(image)
    gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
    re_image = cv2.resize(gray, (size, size))
    return re_image

features = []
for image in glob.glob("samples/*.png"):
    img = transform(image)
    features.append(list(get_hog_features(img)))
    

    

In [3]:

x_test = scaler.transform(np.array(features, dtype ="float32"))


In [4]:
# model.predict(x_test)
x_test.shape

(10, 8100)

In [5]:
features = []
for i in glob.glob("positive_images/*.jpg")[:10]:
    img = transform(i)
    features.append(list(get_hog_features(img)))
    

In [6]:
test = scaler.transform(np.array(features, dtype = "float32"))


In [7]:
model.predict(test)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.], dtype=float32)

In [8]:

test.shape


(10, 8100)

In [14]:
test11 = "test/phone3.jpg"
img = transform(test11)
f = get_hog_features(img)

In [15]:
f = np.array(f, dtype = "float32")


In [16]:
f=f.reshape(1, 8100)
f

array([[0.22153418, 0.006453  , 0.02383736, ..., 0.00308386, 0.00575533,
        0.02590224]], dtype=float32)

In [17]:
f = scaler.transform(f)

In [18]:
model.predict(f)

array([1.], dtype=float32)